DROP USER IF EXISTS 'webserver'@'%';

CREATE USER 'webserver'@'%' IDENTIFIED BY 'X7g9#4vZ1$2cQ5';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON college_events.* TO 'webserver'@'%';

FLUSH PRIVILEGES;
