version: '3.4'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php  # Path to your Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./website_root:/var/www/html
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql  # Path to your Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: college_events
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
