version: '3.4'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php  # Path to your Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./php-code:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      #MYSQL_DATABASE: mydb
      #MYSQL_USER: myuser
      #MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      #PMA_PORT: 3306
      #PMA_USER: myuser
      #PMA_PASSWORD: mypassword
    depends_on:
      - mysql
